---
- hosts: all
  roles:
    - ansible-user
  tags: base-provision

- hosts: web
  roles:
    - provision-java
    - provision-nginx
    - provision-postgres-client
  tags: provision

- hosts: db
  roles:
    - provision-postgres
    - provision-db
  tags: provision

- hosts: web
  roles:
    - deploy-ui
  tags: deploy

- hosts: web
  roles:
    - karumpalakai-server
  tags: deploy

