---
- name: install dependency to manage database and users with ansible
  yum: name=python-psycopg2 state=present
  sudo: yes

- template: src=create_user.psql.j2.j2 dest=/tmp/create_user.psql.j2

- name: Creates an administration user to create/drop databases
  command: su - postgres -c "psql -f /tmp/create_user.psql.j2"
  sudo: yes

- name: Creating database karumpalakai
  postgresql_db: name=karumpalakai
    encoding='UTF-8'
    login_host=localhost
    login_user={{postgresql_superuser_username}}
    login_password={{postgresql_superuser_password}}
    owner={{postgresql_superuser_username}}
    template=template0
